services:
  - type: worker
    name: telegram-shop
    env: python
    plan: starter
    region: frankfurt
    runtime: python-3.12.7
    disk:
      name: shop-data
      mountPath: /data
      sizeGB: 1
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-rus ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: SBER_CARD
        sync: false
      - key: SBER_RECIPIENT
        sync: false
      - key: SBER_BANK
        sync: false
      - key: SUPPORT_USERNAME
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STARS_TO_RUB
        sync: false
      - key: DB_URL
        value: sqlite+aiosqlite:////data/bot.db
