services:
  - type: worker
    name: telegram-shop
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-rus
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: SBER_CARD
        sync: false
      - key: SBER_RECIPIENT
        sync: false
      - key: DB_URL
        value: sqlite+aiosqlite:///data/bot.db
